#!/usr/bin/env python3
# This file is placed in the Public Domain.


"wipe"


import os
import sys


def popen(txt):
    result = ""
    for line in os.popen(txt).readlines():
        result += line.rstrip() + "\n"
    print(result.rstrip())
    sys.stdout.flush()


## runtime


popen("fin/clean")
popen("rm -fR env")

